// <auto-generated />
using System;
using HMQuota.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HMQuota.Migrations
{
    [DbContext(typeof(HMQuotaDBContext))]
    partial class HMQuotaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("HMQuota.Model.QuotaBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createDate");

                    b.Property<int>("headerId");

                    b.Property<DateTime>("lastUpdate");

                    b.Property<string>("quotaString");

                    b.Property<string>("quotaString1");

                    b.Property<string>("quotaString2");

                    b.Property<string>("quotaString3");

                    b.Property<string>("quotaString4");

                    b.Property<string>("quotaString5");

                    b.Property<string>("quotaString6");

                    b.Property<string>("quotaString7");

                    b.Property<string>("quotaString8");

                    b.Property<string>("quotaString9");

                    b.HasKey("Id");

                    b.ToTable("quotaBody");
                });

            modelBuilder.Entity("HMQuota.Model.QuotaHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createDate");

                    b.Property<int>("index");

                    b.Property<DateTime>("lastUpdate");

                    b.Property<string>("quotaName");

                    b.HasKey("Id");

                    b.ToTable("quotaHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
